[phases.setup]
nixPkgs = ["nodejs_20", "vips", "pkg-config", "python3"]

[variables]
SHARP_IGNORE_GLOBAL_LIBVIPS = "1"

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["cd apps/cms && pnpm build"]

[start]
cmd = "cd apps/cms && node dist/server.js"
